### ISSUE TITLE
UI bug with notification icon animation

### ISSUE THREAD

**Issue by artbymungo** [nuken-official/nuken#2]
I got stuck in a weird infinite loop between the notification and tools menu. The megaphone icon kept switching focus to the tools menu when it rotated. Appeared to only happen after opening the script options popup within the tools menu. It was hard to repeat but the attached video might help solve it.
---
nuken - Online editor
Chrome browser (up-to-date)
Linux Ubuntu

https://user-images.githubusercontent.com/18603893/144965988-bcd6641c-5588-45ae-b2c3-326be4894650.mp4

**Comment by nuken-official** [comment]
Thanks for reaching out! We’ve actually solved this issue. It had to do with an option in the Tools Menu overlapping the Announcements Feed icon, causing it to loop back and forth like you’re describing. For whatever reason this issue only became apparent after Dark Mode had been toggled on and off - so reloading the page and sticking to an appearance should keep you in the clear. 

The new version of nuken 7, releasing tomorrow, fixes this issue, alongside a ton of other ones. You can download it early by checkout out our beta: [http://nuken.xyz/beta]

Thanks for your attention to detail, it’s feedback like yours that’s pushed us towards improvement!
